const fs = require('fs')
const path = require('path')

const root = process.cwd()
const outDir = path.join(root, 'out')
const nextDir = path.join(root, '.next')
const pagesDir = path.join(nextDir, 'server', 'pages')
const nextStaticDir = path.join(nextDir, 'static')
const publicDir = path.join(root, 'public')

function copyRecursive(src, dest) {
  if (!fs.existsSync(src)) return
  const stat = fs.statSync(src)
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true })
    for (const entry of fs.readdirSync(src)) {
      copyRecursive(path.join(src, entry), path.join(dest, entry))
    }
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    fs.copyFileSync(src, dest)
  }
}

function copyHtmlPages(srcDir, baseDir = srcDir) {
  if (!fs.existsSync(srcDir)) return

  for (const entry of fs.readdirSync(srcDir)) {
    const srcPath = path.join(srcDir, entry)
    const stat = fs.statSync(srcPath)

    if (stat.isDirectory()) {
      copyHtmlPages(srcPath, baseDir)
      continue
    }

    if (!entry.endsWith('.html')) continue
    if (entry === '_app.html' || entry === '_document.html' || entry === '_error.html') continue

    const relative = path.relative(baseDir, srcPath).replace(/\\/g, '/')
    let destPath

    if (relative === 'index.html') {
      destPath = path.join(outDir, 'index.html')
    } else if (relative === '404.html') {
      destPath = path.join(outDir, '404.html')
    } else if (relative.endsWith('/index.html')) {
      destPath = path.join(outDir, relative)
    } else {
      const withoutHtml = relative.replace(/\.html$/, '')
      destPath = path.join(outDir, withoutHtml, 'index.html')
    }

    fs.mkdirSync(path.dirname(destPath), { recursive: true })
    fs.copyFileSync(srcPath, destPath)
  }
}

if (fs.existsSync(path.join(outDir, 'index.html'))) {
  console.log('Next.js static export already exists in /out. Keeping generated output.')
  process.exit(0)
}

fs.mkdirSync(outDir, { recursive: true })
copyRecursive(publicDir, outDir)
copyRecursive(nextStaticDir, path.join(outDir, '_next', 'static'))
copyHtmlPages(pagesDir)

if (!fs.existsSync(path.join(outDir, 'index.html'))) {
  throw new Error('Static output failed: could not create out/index.html')
}

console.log('Static output prepared in /out, including product detail pages if generated by Next.js.')
